### PR TITLE
Fix 'tabWidth' option setup for formatter

### PR DESCRIPTION
**Pull request by evidolob**
Fix: https://github.com/redhat-developer/vscode-yaml/issues/366

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Comment by joshuawilson** [comment]
Is there a way we can test this?

**Comment by evidolob** [comment]
@joshuawilson I thinking about that, it may take time, as I need to mock `IConnection` somehow.

**Comment by joshuawilson** [comment]
I don't know how to verify that your change will fix the issue. That is why I'm asking for the test. That will prove it and make sure it doesn't break again.

**Comment by JPinkney** [comment]
We can also extract everything out of server.ts so that the server.ts file basically has the hookups to the language features and nothing else. That way all of the other features would technically be abstracted enough that you can test them directly

**Comment by apisim** [comment]
Yeah, probably #305 is the cause for the problem, I'm sorry.

For what it's worth...I think the changes proposed by @evidolob will fix the issue. Not only that but they will remove the tight coupling `server.ts` has with `prettier` - `tabWidth` is specific to `prettier` whereas `tabSize` is the "standard" [FormattingOptions](https://github.com/codedownio/vscode-languageserver-types/blob/e9bdff0a2370afcfcd453330ed09fe7810d06e5d/src/main.ts#L2186) option.

Here is another, I think, [possible solution](https://github.com/redhat-developer/yaml-language-server/compare/master...apimastery:pr-322) that aims to preserve the old behavior (and it keeps the tight coupling). Notice the unit tests. In hindsight, I should have probably coded it that way to begin with:
```
tabWidth: (options.tabWidth as number) || options.tabSize,
```
In my local testing, the formatting still works with this in monaco-yaml in the browser.

**Comment by evidolob** [comment]
@JPinkney Yes, it seems that refactoring `server.ts` is the only way to write tests for it.

@apisim I like your solution more, can you create PR instead of this?

**Comment by apisim** [comment]
Sure, @evidolob. Please see #324.

**Comment by evidolob** [comment]
Closing, as #324 is better.

**Pull request closed without merging**
