### PR TITLE
Fix empty completion list on empty file

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Fixes empty completion list on empty file. I found that we add `holder: \n` text in to text document, if line on which completion called is empty(contains only white spaces and line delimiter). 
Such behaviour do not to allow to choose proper schema, as some(k8's) schemas has `additionalProperties: false`, 
but AST contains property `holder`.
This PR fix that, so if file is empty we add `{}`(empty object)

### What issues does this PR fix or reference?
Fix: https://github.com/redhat-developer/vscode-yaml/issues/349

### Is it tested? How?
Configure vscode-yaml with 
```json
"yaml.schemas": {
    "kubernetes": [
      "kubernetes.yaml"
    ]
}
```
then open `kubernetes.yaml`, file should be empty, and call code completion, you should see :
Screenshot 2020-12-10 at 14 31 13

### CODE REVIEW

**Review by JPinkney — COMMENTED** [review]
I just played around with it and it works great when you have autocomplete on the first line and last line but for some reason it doesn't seem to work if you try to autocomplete on a line in the middle of the file (though I'm not sure if thats related to this PR or not, it might not have been working before)

E.g.
```

<- autocompleteting here

```
seems to not get any results

**Comment by evidolob** [comment]
@JPinkney Yes, that is problem for this PR, going to fix it

**Comment by evidolob** [comment]
@JPinkney Now completion should work on any line of "empty" file

**Review by JPinkney — APPROVED** [review]
Works great!

**Pull request merged**
