### PR TITLE
Add CodeAction to convert Tab characters to spaces

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
This PR adds various things:

- Improves yaml parser diagnostics reporting, now diagnostics has proper text regions
- Collapse multiple `Using tabs can lead to unpredictable results` diagnostic in to one, previously we report each tab character separately
-  Add CodeAction to convert Tab characters to spaces

Demo:

https://user-images.githubusercontent.com/929743/109139137-d68d8a80-7763-11eb-995c-e1cd5e02462c.mov

Convert all tabs to spaces:

https://user-images.githubusercontent.com/929743/109173190-3f88f880-778c-11eb-8f69-acc9ca934657.mov

### What issues does this PR fix or reference?
Fix: #244 

### Is it tested? How?
With new tests and manually, just create yaml file with tab's characters and see that  `Using tabs can lead to unpredictable results` error has CodeAction `Convert Tab to Spaces` and when it executed tabs replaced with spaces according to current editor settings.

### CODE REVIEW

**Comment by evidolob** [comment]
cc @mickaelistria

**Comment by mickaelistria** [comment]
:+1:

**Review by JPinkney — APPROVED** [review]
Just tried it out and everything was working for me! Just wondering if it also makes sense to have a code action with `Convert all tabs to spaces` so we don't have to do it multiple times. I assume if someone has tabs in their yaml file they probably just have a setting enabled that keeps tabs as tabs instead of tabs to spaces

**Comment by evidolob** [comment]
@JPinkney I added `Convert all Tabs to Spaces` action.

**Review by JPinkney — APPROVED** [review]
Tried with the newest changes and everything seemed to be working :+1:

**Pull request merged**
