### PR TITLE
intellisense doesn't work for array item

### PR DESCRIPTION
**Pull request by 928PJY**
if there is no space between `-` and `holder`, the yaml structure will be wrong, so the array intellisense doesn't work

### CODE REVIEW

**Comment by 928PJY** [comment]
Some comments? @JPinkney

**Comment by 928PJY** [comment]
This PR has been inactive for 7 days, can you @JPinkney give some update?

**Comment by JPinkney** [comment]
I have been on vacation.

**Comment by 928PJY** [comment]
oh~ sorry for that

---
In reply to: [418946400](https://github.com/redhat-developer/yaml-language-server/pull/85#issuecomment-418946400) [](ancestors = 418946400)

**Pull request merged**
