### PR TITLE
fix mulitple schema matches in oneOf based on the propertiesMatches value

### PR DESCRIPTION
**Pull request by msivasubramaniaan**
### What does this PR do?

This PR checks the multiple  schema matches under oneOf based on the sub schema properties matches value

### What issues does this PR fix or reference?

https://github.com/redhat-developer/vscode-yaml/issues/683
https://github.com/redhat-developer/yaml-language-server/issues/586

### Is it tested? How?
yes with test cases

### CODE REVIEW

**Comment by evidolob** [comment]
@msivasubramaniaan It seems that you forgot to add tests

**Comment by msivasubramaniaan** [comment]
@evidolob The test case was added https://github.com/redhat-developer/yaml-language-server/pull/623/files as part of this PR.

**Comment by evidolob** [comment]
Then I miss understand the case, if you add tests in #623 and with this changes tests not failing then your test is not correct, please make sure that we have test witch tests changes in this PR.

**Comment by msivasubramaniaan** [comment]
> Then I miss understand the case, if you add tests in #623 and with this changes tests not failing then your test is not correct, please make sure that we have test witch tests changes in this PR.

As part of #623 the given YAML matched both oneOf cases so it didn't fail with the latest fix. But https://github.com/redhat-developer/vscode-yaml/issues/683 the YAML not matched both of given schema in oneOf and some properties are still missing. So with the latest fix the error count will not be 0. There are some test cases which covered the same scenario already

**Review by evidolob — APPROVED** [review]

**Pull request merged**
