### PR TITLE
feat(modeline): Modeline takes precendence over registerContributor API

### PR DESCRIPTION
**Pull request by jpinkney-aws**
### What does this PR do?
Problem:
- Right now, when a file is watched by the registerContributor API a user has no way of overriding that schema. In certain cases, a user may want to override the schema provided by the registerContributor API on a file by file basis.

Solution:
- Make the modeline become a higher priority then the registerContributor API. That way users have the ability to always override the schema for the given file.

### What issues does this PR fix or reference?
https://github.com/aws/aws-toolkit-vscode/issues/3012

### CODE REVIEW

**Comment by justinmk3** [comment]
Any documentation/readme updates needed?

**Comment by hoffa** [comment]
For context, this is affecting https://github.com/aws/serverless-application-model/discussions/2645

**Comment by gorkem** [comment]
Hey, welcome back @jpinkney-aws :) 

The suggested priority order makes sense. I will review it ASAP but can you also add a note to the README that modeline will override the extensions?

**Review by gorkem — APPROVED** [review]
LGTM, may need a rebase but otherwise it is good.

**Comment by gorkem** [comment]
@msivasubramaniaan Can you complete the review for this?

**Review by msivasubramaniaan — APPROVED** [review]
LGTM

**Pull request merged**
