### PR TITLE
feat: add multiple schema deletions

### PR DESCRIPTION
**Pull request by p-spacek**
### What does this PR do?
add schema modification to delete schemas from cache.
```ts
export enum MODIFICATION_ACTIONS {
  'delete',
  'add',
  'deleteWhole',
}
```

#### Motivation:
when dynamically changing shared schema, I use this deleteWhole schema action to delete old parent schemas from cache. So language server will reload parents schemas with updated referenced schema. 

### What issues does this PR fix or reference?
no ref

### Is it tested? How?
added unit test

### CODE REVIEW

**Review by JPinkney — COMMENTED** [review]
It looks good to me, my only suggestion would be to change deleteWhole to deleteAll or something like that

**Comment by p-spacek** [comment]
agree, had deleteAll before, but I overthink it...
renamed

**Review by JPinkney — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Comment by evidolob** [comment]
@p-spacek Can you update this PR. I'm going to merge it after.

**Comment by p-spacek** [comment]
Sorry I didn't notice.
Resolved

**Comment by evidolob** [comment]
@p-spacek No problem. Thank you, for your contribution!

**Pull request merged**
