### PR TITLE
Release '0.14.0'

### PR DESCRIPTION
**Pull request by evidolob**

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]
Just approved, but I'm not sure if we're blocked from releasing too close to the Holidays or not

**Comment by evidolob** [comment]
@JPinkney I don't know about blocking. I'm going on PTO for two weeks, do you think that we can make release when I return?

**Comment by JPinkney** [comment]
Yeah, that works. Or I can release on Jan 4th

**Comment by evidolob** [comment]
OK then, this release is up to you

**Review by joshuawilson — APPROVED** [review]

**Comment by JPinkney** [comment]
I didn't end up doing the release, but we can probably add https://github.com/redhat-developer/yaml-language-server/pull/384 to the CHANGELOG and wait for https://github.com/redhat-developer/yaml-language-server/pull/385/files to come through since it's almost done

**Comment by evidolob** [comment]
@JPinkney Sure, I will update this with new changes

**Comment by evidolob** [comment]
@JPinkney @joshuawilson 
I've update CHANGELOG, I think we are ready for release.

**Review by JPinkney — APPROVED** [review]

**Pull request merged**
