### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by urohit011**
### What does this PR do?
Adds a dockerfile so the laguage server could be run in a container

### What issues does this PR fix or reference?
related to #335

### CODE REVIEW

**Review by evidolob — APPROVED** [review]
LGTM

**Comment by JPinkney** [comment]
Are there any special commands to get this working? I tried:
```
docker build . -t quay.io/jpinkney/yaml-language-server
docker run quay.io/jpinkney/yaml-language-server:latest
```
but within a few seconds the container stops:
```
docker ps -a

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
d24f122c1657        9768037c9eb0        "node ./out/server/s…"   6 minutes ago       Exited (1) 6 minutes ago                       sharp_hopper
```

**Comment by urohit011** [comment]
Hi @JPinkney , I think you should try running the docker image interactively with the command 

`docker run -it quay.io/jpinkney/yaml-language-server:latest`, 

by default it will run with `--stdio` if you want to run it with `node-ipc` you should try 

`docker run -it quay.io/jpinkney/yaml-language-server:latest --node-ipc`

**Review by JPinkney — APPROVED** [review]

**Comment by joshuawilson** [comment]
@JPinkney @evidolob Do think this needs something in the README or another doc?

**Comment by evidolob** [comment]
I think yes, we need some README update for this.

**Comment by JPinkney** [comment]
We will also most likely need CI since this isn't technically hosted anywhere right now. I can make a PR that adds the CI and updates the readme with where the image will live

**Review by joshuawilson — APPROVED** [review]

**Comment by urohit011** [comment]
Thank you @JPinkney @joshuawilson and @joshuawilson for reviewing it.

**Pull request merged**
