### PR TITLE
Adding test for autocompletion for Camel K schema

### PR DESCRIPTION
**Pull request by apupier**
created on request https://github.com/redhat-developer/vscode-yaml/issues/310#issuecomment-653164457

### CODE REVIEW

**Comment by apupier** [comment]
> Is there any reason why we need to bring in chai? I guess its technically easier but adding one dependency for 2 tests seems like a lot

it is technically easier. Chai is a relatively common library used for test assertion (3M+ downloads https://www.npmjs.com/package/chai ). I'm not familiar with TypeScript language, so using this kind of utilities saves me a lot of time.
The dependency is only for test, not at runtime.

**Comment by apupier** [comment]
By the way I opened this PR on request to emphasize that there is a difference between the yaml laanguage server and the VS Code yaml behavior.

i'm not sure that it is worthy to merge it as-is

**Comment by joshuawilson** [comment]
Can we close this? or update it with the intent to merge.

**Comment by apupier** [comment]
this would need to be reworked and no time for that currently. Closing

**Pull request closed without merging**
