### PR TITLE
Don't apply local schema to file itself

### LINKED ISSUE #871: Local YAML schema applied to itself
## Describe the bug

Related to https://github.com/redhat-developer/vscode-yaml/issues/894.

I'm using YAML VSCode extension.
I wrote a custom YAML schema in a project and associate its schema to some files in the project using VSCode setting like below.

```
// .vscode/settings.json
// ...
  "yaml.schemas": {
    "./schemas/custom.yml": [ "./a/config.yml", "./b/config.yml" ]
  }
// ...
```

Though `./schemas/custom.yml` is applied to `./{a,b}/config.yml`, but it is also applied to `./schemas/custom.yml` itself.

## Expected Behavior

The schema `./schemas/custom.yml` is NOT applied to `schemas/custom.yml` itself.

## Current Behavior

The schema `./schemas/custom.yml` is NOT applied to `schemas/custom.yml` itself.

## Steps to Reproduce

1. Open a project in VSCode (YAML extension was installed)
2. Write custom YAML schema `schemas/custom.yml`
3. Associate the schema to some files by `"yaml.schemas"` setting in `.vscode/settings.json`

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

### PR DESCRIPTION
**Pull request by odiak**
### What does this PR do?

Prevent local schema from being applied to file itself unless explicitly enabled.

Previously, when editing local schema file, the schema was applied to the file itself.
Such self association was introduced on #282 mainly for testing.

I introduced a flag `associateSchemaItself` to `SettingsState` to control that behavior.

### What issues does this PR fix or reference?

- Fixes #871.
- Related to redhat-developer/vscode-yaml/issues/894.

### Is it tested? How?

I tested this together with [vscode-yaml](https://github.com/redhat-developer/vscode-yaml), according to [its contribution guide](https://github.com/redhat-developer/vscode-yaml/blob/main/CONTRIBUTING.md).

#### Step 1: Modify `vscode-yaml/.vscode/launch.json` like below to debug on a workspace.

```diff
      {
        // A launch configuration that compiles the extension and then opens it inside a new window
        "name": "Launch Extension",
        "type": "extensionHost",
        "request": "launch",
        "runtimeExecutable": "${execPath}",
-       "args": ["--extensionDevelopmentPath=${workspaceRoot}"],
+       "args": ["--extensionDevelopmentPath=${workspaceRoot}", "${env:HOME}/my-test-workspace"],
```

#### Step 2: Build

```
cd yaml-language-server
yarn run build
```

#### Step 4: Write some files on newly opened window

foo.yml:
```yml
hello: world
```

schema.yml:
```yml
type: object
properties:
  hello:
    type: string
additionalProperties: false
```

.vscode/settings.json:
```json
{
  "yaml.schemas": {
    "schema.yml": ["foo.yml"]
  }
}
```

#### Step 5: Check

- Open `foo.yaml` and confirm that `schema.yml` is applied.
  - Optionally check if validation works by adding some properties.
- Open `schema.yml` and confirm that no schema is applied (and there are no validation errors).

### CODE REVIEW

**Comment by gorkem** [comment]
Thank you for the PR. When I think about this I can not really find a good reason to continue to maintain this feature. For tests, I think we can drop this feature and use a customSchemaProvider to do the mapping.

**Comment by odiak** [comment]
I also considered using customSchemaProvider, but it required a lot of changes for tests.
So I gave up for it and tried to find a way with less changes.

**Comment by odiak** [comment]
How about merging this first to fix problem, and remove the flag later?

**Comment by gorkem** [comment]
I have done a new PR that updates how the tests work and removes the hack from SchemaProvider. Can you test PR https://github.com/redhat-developer/yaml-language-server/pull/898 and see if it works for you?

**Comment by odiak** [comment]
@gorkem Thanks! It looks good for me.

**Pull request closed without merging**
