### PR TITLE
fix: add indentation when parsing example as string

### PR DESCRIPTION
**Pull request by AceTheCreator**
### What does this PR do?
Enhanced how examples are being parsed as a plain string 

### What issues does this PR fix or reference?
#889

### CODE REVIEW

**Comment by AceTheCreator** [comment]
Hey, @msivasubramaniaan, can you look into this PR?

**Review by gorkem — APPROVED** [review]
LGTM. 

Thank you for your contribution

**Review by msivasubramaniaan — APPROVED** [review]
LGTM

Thanks for the contribution @AceTheCreator

**Comment by AceTheCreator** [comment]
@msivasubramaniaan @gorkem any idea when the next release will happen?

**Pull request merged**
