### PR TITLE
Fix opening local schema on windows

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Fix opening local schema on windows with codelens.

### What issues does this PR fix or reference?
Fix https://github.com/redhat-developer/vscode-yaml/issues/513

### Is it tested? How?
with unit test

### CODE REVIEW

**Comment by JPinkney** [comment]
I just tried this on windows and it doesn't seem like it's jumping to the schema. This was the trace log:
```
[Trace - 9:15:58 a.m.] Received response 'textDocument/codeLens - (41)' in 8ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 0
            }
        },
        "command": {
            "title": "Gitlab CI configuration (components.json_schema.json)",
            "command": "jumpToSchema",
            "arguments": [
                "C:\\Users\\Josh\\Documents\\Schemas\\components.json_schema.json"
            ]
        }
    }
]


[Trace - 9:16:03 a.m.] Sending request 'workspace/executeCommand - (42)'.
Params: {
    "command": "jumpToSchema",
    "arguments": [
        "C:\\Users\\Josh\\Documents\\Schemas\\components.json_schema.json"
    ]
}


[Trace - 9:16:03 a.m.] Received request 'window/showDocument - (36)'.
Params: {
    "uri": "C:\\Users\\Josh\\Documents\\Schemas\\components.json_schema.json",
    "external": false,
    "takeFocus": true
}


[Trace - 9:16:03 a.m.] Sending response 'window/showDocument - (36)'. Processing request took 3ms
Result: {
    "success": true
}


[Trace - 9:16:03 a.m.] Received response 'workspace/executeCommand - (42)' in 7ms.
No result returned.
```

**Comment by evidolob** [comment]
@JPinkney 
This request
```
[Trace - 9:16:03 a.m.] Received request 'window/showDocument - (36)'.
Params: {
    "uri": "C:\\Users\\Josh\\Documents\\Schemas\\components.json_schema.json",
    "external": false,
    "takeFocus": true
}

``` 

Should open file in editor `components.json_schema.json` VSCode wasn't do that?

**Comment by JPinkney** [comment]
For some reason, it wasn't opening. The computer I was testing on might be on an old vscode version. I'll try again in ~30 minutes

**Comment by JPinkney** [comment]
I just checked my VSCode version and it's the latest. For some reason VSCode just won't open those paths. I tried doing something like:
```javascript
if (!uri.startsWith('file') && !/^[a-z]:[\\/]/i.test(uri)) {
  const origUri = URI.parse(uri);
  const customUri = URI.from({
    scheme: 'json-schema',
    authority: origUri.authority,
    path: origUri.path.endsWith('.json') ? origUri.path : origUri.path + '.json',
    fragment: uri,
  });
  uri = customUri.toString();
} else if (/^[a-z]:[\\/]/i.test(uri)) {
  uri = 'file:///' + uri;
}
````

and it seems to open the uri but instead of showing the top of the schema it shows the very bottom

**Comment by evidolob** [comment]
@JPinkney I finally manage to get windows to fix this, now it should work.

**Review by JPinkney — APPROVED** [review]
Just re-tested on windows and everything looks good to me

**Pull request merged**
