### PR TITLE
Remove jenkinsfile since it's no longer needed

### PR DESCRIPTION
**Pull request by JPinkney**
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

### What does this PR do?
This PR removes the jenkinsfile because it's no longer used for anything

### CODE REVIEW

**Comment by joshuawilson** [comment]
You no longer use the Red Hat CI server to build/release this?

**Comment by JPinkney** [comment]
Not as far as I know, unless @evidolob added them to a different jenkins instance. I think the only reason we had the Jenkinsfile was to build a tar for Che 6. The last successful build was August 6th 2020

**Review by evidolob — APPROVED** [review]
We do not use this `Jenkinsfile` anymore.

**Comment by evidolob** [comment]
> Not as far as I know, unless @evidolob added them to a different jenkins instance. I think the only reason we had the Jenkinsfile was to build a tar for Che 6. The last successful build was August 6th 2020

The only `Jenkinsfile` which we use is on `vscode-yaml`, we use it for release

**Review by joshuawilson — APPROVED** [review]

**Pull request merged**
